# Copyright 2025 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

from typing import Any, Sequence, NamedTuple, Optional
import torch
import math
from ..exports.signature import OpSignature


class LayerNormSignatureStorage(NamedTuple):
    input_shape: list[int]
    normalized_shape: list[int]
    eps: float
    elementwise_affine: bool
    bias: bool
    dtype: torch.dtype
    # TODO: mode is currently in conv_exports/conv.py


class LayerNormSignature(OpSignature):
    def __init__(
        self,
        *,
        input_shape: Sequence[int],
        normalized_shape: Sequence[int],
        eps: float = 1e-5,
        elementwise_affine: bool = True,
        bias: bool = True,
        dtype=torch.bfloat16,
    ):
        if (
            len(normalized_shape) > len(input_shape)
            or input_shape[-len(normalized_shape) :] != normalized_shape
        ):
            raise ValueError(
                f"expected normalized shape to contain the trailing dimensions of the input shape, got {input_shape=}, {normalized_shape=}"
            )

        self._signature = LayerNormSignatureStorage(
            input_shape=input_shape,
            normalized_shape=normalized_shape,
            eps=eps,
            elementwise_affine=elementwise_affine,
            bias=bias,
            dtype=dtype,
        )

    # TODO(azinenko): this looks rather dirty...
    def __getattr__(self, name: str) -> Any:
        return self._signature.__getattribute__(name)

    @property
    def output_shape(self) -> list[int]:
        return self._signature.input_shape

    @staticmethod
    def get(
        input: torch.Tensor,
        normalized_shape: int | Sequence[int] | torch.Size,
        weight: Optional[torch.Tensor] = None,
        bias: Optional[torch.Tensor] = None,
        **kwargs,
    ) -> "LayerNormSignature":
        normalized_shape_list = (
            list(normalized_shape)
            if not isinstance(normalized_shape, int)
            else [normalized_shape]
        )
        assert (
            weight is None or list(weight.shape) == normalized_shape_list
        ), f"Expected the weight tensor to have {normalized_shape=}, got {weight.shape}."
        assert (
            bias is None or list(bias.shape) == normalized_shape_list
        ), f"Expected the bias tensor to have {normalized_shape=}, got {bias.shape}."
        assert (
            bias is None or weight is not None
        ), f"Expected the bias tensor to be provided only if the weight tensor is."
        if weight:
            assert weight.dtype == input.dtype
        if bias:
            assert weight.dtype == bias.dtype
        return LayerNormSignature(
            input_shape=list(input.shape),
            normalized_shape=normalized_shape_list,
            elementwise_affine=weight is not None,
            bias=bias is not None,
            dtype=input.dtype,
            **kwargs,
        )

    # TODO: conv has a standalone version of this that is cached...
    def get_func_name(self) -> str:
        # XXX: this must exactly match the name generated by the compiler, e.g.
        # layer_norm_3d_bfloat16_42x12x45x13_w_b.
        name_items = [
            "layer_norm",
            f"{len(self.normalized_shape)}d",
            str(self.dtype).removeprefix("torch."),
            "x".join(str(i) for i in self.input_shape),
            "w" if self.elementwise_affine is not None else "",
            "b" if self.bias is not None else "",
        ]
        return "_".join(name_items)

    def get_output_size(self) -> int:
        return math.prod(self.output_shape) * int(self.dtype.itemsize)

    def get_nn_module(self, use_custom: bool) -> torch.nn.Module:
        # TODO: this is specific to conv and may need to be refactored further
        assert use_custom, "skipping use_custom not supported for layernorm"
        # TODO: support modes
        return LayerNormForward(self)

    def get_sample_args(
        self,
        *,
        device: str | torch.device | None = None,
        splat_value: int | float | None = None,
        seed: Optional[int] = None,
    ) -> (
        tuple[torch.Tensor]
        | tuple[torch.Tensor, torch.Tensor]
        | tuple[torch.Tensor, torch.Tensor, torch.Tensor]
    ):
        gen = torch.Generator(device=device)
        if seed:
            gen = gen.manual_seed(seed)

        def get(shape: Sequence[int]) -> torch.Tensor:
            if splat_value is not None:
                return torch.ones(shape, dtype=self.dtype, device=device) * splat_value
            return torch.randn(shape, generator=gen, dtype=self.dtype, device=device)

        # TODO: support modes
        args = [get(self.input_shape)]
        if self.elementwise_affine:
            args.append(get(self.normalized_shape))
        if self.bias:
            args.append(get(self.normalized_shape))
        return tuple(args)


class LayerNormForward(torch.nn.Module):
    def __init__(self, signature: LayerNormSignature):
        super().__init__()
        self.normalized_shape = signature.normalized_shape
        # TODO(azinenko): it is rather fishy that the signature includes values
        # such as eps that are not actually part of the funciton signature...
        self.eps = signature.eps

    def forward(
        self,
        input: torch.Tensor,
        weight: torch.Tensor | None = None,
        bias: torch.Tensor | None = None,
    ) -> torch.Tensor:
        return torch.layer_norm(input, self.normalized_shape, weight, bias, self.eps)
