[package]
name = "aplp"
version = "0.1.0"
edition = "2021"

[lib]
name = "aplp_lib"
crate-type = ["cdylib"] # Compile to a C-compatible dynamic library

[dependencies]
rayon = "1.5" # For parallelism
pyo3 = { version = "0.21", features = ["extension-module"] }
