version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python -m pip install .

python:
  install:
    - requirements: docs/api_docs/requirements.txt
    - requirements: pytorch-cpu-requirements.txt

sphinx:
  configuration: docs/api_docs/conf.py
