name: Turbine Unit Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        version: [3.11]
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}
    steps:
      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: ${{matrix.version}}

      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: Sync source deps
        run: |
          python -m pip install --upgrade pip
          # Note: We install in three steps in order to satisfy requirements
          # from non default locations first. Installing the PyTorch CPU
          # wheels saves multiple minutes and a lot of bandwidth on runner setup.
          pip install -r pytorch-cpu-requirements.txt
          pip install --upgrade \
            -r requirements.txt \
            -r mypy-requirements.txt
          pip install -e .[testing]

      - name: Run core tests
        if: ${{ !cancelled() }}
        run: |
          pytest -n 4 ./

      - name: MyPy Type Checking Core
        if: ${{ !cancelled() }}
        run: mypy
